---
swagger: "2.0"
info:
  description: "Este é o swagger da API desenvolvida para o processo seletivo da vaga de \
  estagiário em desenvolvimento de software da BGC Brasil."
  version: "1.0.0"
  title: "Swagger API mais vendidos da Amazon por categoria"
  contact:
    email: "ricardoemanuelde@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "ricardo-emanuel01.github.io/bgc-internship-swagger/"
basePath: "/dev"
tags:
- name: "items"
  description: "Produtos mais vendidos da Amazon por categoria e data"

schemes:
- "https"
paths:
  /items:
    get:
      tags:
      - "items"
      summary: ""
      description: ""
      operationId: "uploadFile"
      produces:
      - "application/json"
      parameters:
      - name: "category"
        in: "query"
        description: "Categoria dos itens"
        required: false
        type: "string"
        enum:
        - "books"
        - "electronics"
        - "computers"
        - "videogames"
        default: ""
      - name: "date"
        in: "query"
        description: "Data da obtenção do dado no formato AAAA-MM-DD"
        required: false
        type: "string"
        default: "2023-11-30"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
