---
swagger: "2.0"
info:
  description: "Este é o swagger da API desenvolvida para o processo seletivo da vaga de \
  estagiário em desenvolvimento de software da BGC Brasil."
  version: "1.0.5"
  title: "Swagger API mais vendidos da Amazon por categoria"
  contact:
    email: "ricardoemanuelde@gmail.com"
  license:
    name: "MIT"
    url: "https://mit-license.org/"
host: "mbfqtno09c.execute-api.sa-east-1.amazonaws.com"
basePath: "/dev"
tags:
- name: "items"
  description: "Produtos mais vendidos da Amazon por categoria e data"

schemes:
- "https"
paths:
  /items:
    get:
      tags:
      - "items"
      summary: ""
      description: ""
      operationId: "get-items"
      produces:
      - "application/json"
      parameters:
      - name: "category"
        in: "query"
        description: "Categoria dos itens"
        required: false
        type: "string"
        enum:
        - "books"
        - "electronics"
        - "computers"
        - "videogames"
        default: ""
      - name: "date"
        in: "query"
        description: "Data do ranking"
        required: false
        type: "string"
        format: "date"
        default: "2023-11-30"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
definitions:
  ApiResponse:
    type: "object"
    properties:
      message:
        type: "string"
        example: "Successfully retrieved items."
      data:
        type: "array"
        items:
          $ref: "#/definitions/Item"
  Item:
    type: "object"
    properties:
      itemId:
        type: "string"
        example: "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx"
        description: "UUID que identifica o item no banco de dados"
      title:
        type: "string"
        description: "Título do produto no site da Amazon"
      rankingMarket:
        type: "string"
        enum:
        - "1"
        - "2"
        - "3"
        description: "Posição no ranking de sua categoria no momento da obtenção do dado"
      dateOfInsertion:
        type: "string"
        format: "date"
        example: "2023-11-30"
        description: "Data representativa na qual o produto estava no ranking"
      category:
        type: "string"
        enum:
        - "books"
        - "computers"
        - "videogames"
        - "electronics"
        description: "Categoria do produto"
      price:
        type: "integer"
        format: int64
        description: "Os preços disponibilizados contém duas casas decimais mas utilizam representação em número inteiro para evitar problemas de precisão"
          

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
